# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e1c9af4e29665cce9bbd9fa52cd218afadf9fc63849165adab1356a96e5d59a8cbdbc2e5b8fd249b71fbceefe0c73c06c42111e93a9c63b30038bb9da9a8a8d

test:
  secret_key_base: b2b4e650cbcfdbf583ec9bbbfe8177411c331ba01d31d22edbe88517dd7b3b431444b957662e13c7b1e474809fe7d5d5334fba5b2b1d56a39333dafb569505c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
